#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  --set=app_password="$OKNO_DB_APP_PASSWORD" --set=migrator_password="$OKNO_DB_MIGRATOR_PASSWORD" <<'EOSQL'
CREATE ROLE okno_migrator LOGIN PASSWORD :'migrator_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE okno_app LOGIN PASSWORD :'app_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT CONNECT ON DATABASE okno TO okno_migrator, okno_app;
GRANT USAGE, CREATE ON SCHEMA public TO okno_migrator;
GRANT USAGE ON SCHEMA public TO okno_app;
ALTER DEFAULT PRIVILEGES FOR ROLE okno_migrator IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO okno_app;
ALTER DEFAULT PRIVILEGES FOR ROLE okno_migrator IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO okno_app;
EOSQL
