/* Local browser acceptance test. Uses Playwright installed with Python runtime. */
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || '../.venv/Lib/site-packages/playwright/driver/package');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const evidence = path.join(root, 'docs', 'evidence');
fs.mkdirSync(evidence, {recursive:true});

(async () => {
  console.log('Launching local acceptance flow');
  const browser = await chromium.launch({headless:true,args:process.env.CHROMIUM_HOST_IP ? ['--host-resolver-rules=MAP localhost '+process.env.CHROMIUM_HOST_IP] : []});
  const context = await browser.newContext({viewport:{width:1440,height:1000},locale:'pl-PL',ignoreHTTPSErrors:!!process.env.OKNO_TEST_LOCAL_CA,recordVideo:process.env.RECORD_VIDEO ? {dir:'/tmp/okno-video',size:{width:1440,height:1000}} : undefined});
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const consoleErrors=[];
  const expectedConsoleErrors=[];
  let injectedDecisionFailure=false;
  page.on('console', msg => { if(msg.type()==='error') {
    if(injectedDecisionFailure&&msg.text().includes('429')&&expectedConsoleErrors.length===0)expectedConsoleErrors.push(msg.text());
    else consoleErrors.push(msg.text());
  } });
  const report = {tested_at:new Date().toISOString(),base_url:process.env.OKNO_URL||'http://localhost:18430',flows:[],axe:[],responsive:[],page_errors:errors,console_errors:consoleErrors,expected_console_errors:expectedConsoleErrors};
  report.flows.push=(...items)=>{console.log(items.join('\n'));return Array.prototype.push.apply(report.flows,items)};
  const scan = async (name) => {
    const axePath = path.join(root,'.runtime','axe.min.js');
    if(!fs.existsSync(axePath)) throw new Error('Install pinned axe-core with scripts/browser-docker.ps1 first');
    if(fs.existsSync(axePath)) {
      await page.evaluate(fs.readFileSync(axePath,'utf8'));
      const result=await page.evaluate(async()=>window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));
      report.axe.push({screen:name,violations:result.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});
    }
  };
  try {
    await page.goto(report.base_url,{waitUntil:'networkidle',timeout:60000});
    await page.getByRole('combobox',{name:'Wybierz przykład'}).waitFor({timeout:30000});
    await scan('start');
    await page.keyboard.press('Tab');
    if(await page.locator(':focus').innerText()!=='Przejdź do treści') throw new Error('Keyboard skip link is not first focus target');
    await page.keyboard.press('Enter');
    await page.getByRole('button',{name:'Dodaj ofertę lub zajęcia',exact:true}).click();
    await page.getByLabel('Nazwa oferty lub zajęć',{exact:true}).fill('Własna oferta testowa');
    await page.getByLabel('Miejsce (krótka etykieta)').fill('dom');
    await page.getByRole('button',{name:'Sprawdź mój plan',exact:true}).click();
    await page.getByRole('heading',{name:'Konflikt i możliwe zmiany'}).waitFor({timeout:45000});
    if(await page.locator('.alternative').count()) throw new Error('Missing required start must not produce a feasible alternative');
    await scan('missing-data');
    await page.getByRole('button',{name:/Twój plan Godziny/}).click();
    await page.getByLabel('Początek zajęć',{exact:true}).fill('08:00');
    await page.getByRole('button',{name:'Sprawdź mój plan',exact:true}).click();
    await page.locator('.alternative').first().waitFor({timeout:45000});
    report.flows.push('Own offer entry: missing start blocked, completed own offer solved');
    await page.getByRole('button',{name:/Twój plan Godziny/}).click();
    await page.getByRole('combobox',{name:'Wybierz przykład'}).selectOption('single-parent');
    const replace=page.getByRole('button',{name:'Otwórz przykład',exact:true});
    if(await replace.isVisible()) await replace.click();
    await page.getByRole('button',{name:'Sprawdź mój plan',exact:true}).click();
    await page.getByRole('heading',{name:'Konflikt i możliwe zmiany'}).waitFor({timeout:45000});
    const alternatives=page.locator('.alternative');
    await alternatives.first().waitFor({timeout:30000});
    if(await alternatives.count()<2) throw new Error('Expected minimum-change and buffer alternatives');
    if(!((await page.locator('.conflict-card').innerText()).includes('45'))) throw new Error('Expected 45-minute conflict');
    await scan('results');
    await page.screenshot({path:path.join(evidence,'results-desktop.png'),fullPage:true});
    await page.locator('.conflict-card').scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(evidence,'presentation-results.png')});
    report.flows.push('Synthetic demo: conflict45, two calculated alternatives');
    for(const width of [360,320]) {
      await page.setViewportSize({width,height:900});
      const size=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));
      report.responsive.push({width,...size,passes:size.scroll<=size.width+1});
      await scan('results-'+width);
      if(width===360) await page.screenshot({path:path.join(evidence,'results-mobile.png'),fullPage:true});
    }
    await page.setViewportSize({width:1440,height:1000});
    await page.evaluate(()=>{document.documentElement.style.zoom='2'});
    const zoomSize=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));
    report.responsive.push({zoom:'CSS 200%',...zoomSize,passes:zoomSize.scroll<=zoomSize.width+1});
    await page.screenshot({path:path.join(evidence,'results-zoom-200.png')});
    await page.evaluate(()=>{document.documentElement.style.zoom='1'});
    await page.getByRole('button',{name:'Przejdź do uzgodnień'}).click();
    await scan('agreements');
    await page.getByRole('button',{name:'Zobacz dokładny podgląd',exact:true}).click();
    await page.getByTitle('Dokładna treść karty odbiorcy').waitFor({timeout:30000});
    const previewText=await page.frameLocator('iframe').locator('body').innerText();
    if(!previewText.includes('08:15')) throw new Error('Recipient preview missing proposed work hours');
    for(const label of ['Dziecko A','Placówka demonstracyjna','Samotna opieka']) if(previewText.includes(label)) throw new Error('Private label in employer preview');
    const pdfPromise=page.waitForEvent('download',{timeout:45000});
    await page.getByRole('button',{name:'PDF',exact:true}).click();
    const pdf=await pdfPromise;
    fs.writeFileSync(path.join(evidence,'employer-card.pdf'),fs.readFileSync(await pdf.path()));
    if(fs.readFileSync(path.join(evidence,'employer-card.pdf')).subarray(0,4).toString()!=='%PDF') throw new Error('Invalid exported PDF');
    report.flows.push('Exact recipient preview and actual PDF download');
    await page.screenshot({path:path.join(evidence,'agreements-desktop.png'),fullPage:true});
    await page.locator('.export-panel').scrollIntoViewIfNeeded();
    await page.locator('.export-panel').screenshot({path:path.join(evidence,'presentation-card.png')});
    await page.getByRole('button',{name:'Zapisz plan świadomie',exact:true}).click();
    await page.getByRole('checkbox',{name:'Chcę zapisać te dane i rozumiem sposób dostępu.'}).check();
    await page.getByRole('button',{name:'Zapisz mój plan',exact:true}).click();
    await page.getByRole('dialog').waitFor({state:'hidden',timeout:45000});
    await page.getByRole('button',{name:'Akceptacja',exact:true}).first().click();
    await page.getByRole('textbox',{name:'Kto podjął decyzję (rola)'}).fill('Pracodawca');
    const decisionPath=/\/api\/plans\/[^/]+\/decisions$/;
    await page.route(decisionPath,async route=>{
      injectedDecisionFailure=true;
      await route.fulfill({status:429,contentType:'application/json',headers:{'Retry-After':'3'},body:JSON.stringify({detail:'Obliczenia są zajęte. Spróbuj ponownie.'})});
    },{times:1});
    await page.getByRole('button',{name:'Zapisz odpowiedź',exact:true}).click();
    const decisionAlert=page.getByRole('dialog').getByRole('alert');
    await decisionAlert.waitFor();
    if(!(await decisionAlert.innerText()).includes('Obliczenia są zajęte'))throw new Error('Decision error is not visible inside its dialog');
    await page.waitForFunction(()=>document.activeElement?.getAttribute('role')==='alert'&&!!document.activeElement.closest('[role="dialog"]'));
    if(await page.getByRole('textbox',{name:'Kto podjął decyzję (rola)'}).inputValue()!=='Pracodawca')throw new Error('Decision input lost after rejected request');
    if(await page.getByRole('button',{name:'Zapisz odpowiedź',exact:true}).isDisabled())throw new Error('Decision cannot be retried');
    await page.screenshot({path:path.join(evidence,'decision-error-dialog.png')});
    report.decision_error_recovery={injected_status:429,error_visible_in_dialog:true,focus_on_alert:true,input_retained:true,retry_uses_real_api:true};
    injectedDecisionFailure=false;
    const retriedDecision=page.waitForResponse(response=>decisionPath.test(new URL(response.url()).pathname)&&response.request().method()==='POST');
    await page.getByRole('button',{name:'Zapisz odpowiedź',exact:true}).click();
    const decisionResponse=await retriedDecision;
    if(!decisionResponse.ok())throw new Error('Real decision retry failed: '+decisionResponse.status());
    report.decision_error_recovery.retry_status=decisionResponse.status();
    await page.getByRole('dialog').waitFor({state:'hidden',timeout:45000});
    report.flows.push('Explicit save and acceptance with versioned decision');
    await page.getByRole('button',{name:'Przejdź do próby',exact:true}).click();
    await page.getByLabel('Początek okresu odniesienia',{exact:true}).fill('2026-09-28');
    await page.getByLabel('Koniec okresu odniesienia',{exact:true}).fill('2026-10-02');
    await page.getByLabel('Faktycznie przepracowane godziny',{exact:true}).fill('20');
    await page.getByLabel('Koszt opieki i podróży (zł)',{exact:true}).fill('100');
    await page.getByLabel('Czas na organizowanie (min)',{exact:true}).fill('60');
    await page.getByRole('button',{name:'Rozpocznij próbę',exact:true}).click();
    await page.getByRole('heading',{name:'Twój okres odniesienia',exact:true}).waitFor({timeout:45000});
    const actualHours=page.getByLabel('Faktyczna praca tego dnia (godz.)',{exact:true});
    if(await actualHours.inputValue()!=='') throw new Error('Actual outcomes were prefilled from simulation');
    await actualHours.fill('8');
    await page.getByLabel('Koszt opieki i podróży tego dnia (zł)',{exact:true}).fill('25');
    await page.getByLabel('Organizowanie tego dnia (min)',{exact:true}).fill('15');
    await page.getByRole('button',{name:'Zapisz rzeczywistą obserwację',exact:true}).click();
    await page.getByRole('table',{name:'Zapisane obserwacje z próby'}).waitFor({timeout:30000});
    report.flows.push('Baseline, confirmed trial, initially blank outcome and saved synthetic observation');
    await scan('trial');
    await page.screenshot({path:path.join(evidence,'trial-desktop.png'),fullPage:true});
    await page.getByRole('button',{name:'Podejrzyj zdarzenia',exact:true}).click();
    await page.getByRole('button',{name:'Pobierz ICS',exact:true}).waitFor({timeout:30000});
    const icsPromise=page.waitForEvent('download',{timeout:30000});
    await page.getByRole('button',{name:'Pobierz ICS',exact:true}).click();
    const ics=await icsPromise; fs.writeFileSync(path.join(evidence,'trial-calendar.ics'),fs.readFileSync(await ics.path()));
    if(!fs.readFileSync(path.join(evidence,'trial-calendar.ics'),'utf8').includes('BEGIN:VEVENT')) throw new Error('ICS contains no events');
    report.flows.push('Actual calendar export');
    await page.getByRole('button',{name:/Zapisane plany/}).click();
    await page.getByRole('button',{name:'Bieżący plan',exact:true}).click();
    const backupPromise=page.waitForEvent('download');
    await page.getByRole('button',{name:'Pobierz własną kopię JSON',exact:true}).click();
    const backup=await backupPromise; const backupData=fs.readFileSync(await backup.path());
    await page.getByRole('button',{name:'Usuń bieżący plan',exact:true}).click();
    await page.getByRole('button',{name:'Usuń plan i powiązane dane',exact:true}).click();
    await page.getByRole('dialog').waitFor({state:'hidden',timeout:30000});
    await page.getByLabel('Wybierz kopię planu JSON',{exact:true}).setInputFiles({name:'okno-test-backup.json',mimeType:'application/json',buffer:backupData});
    await page.getByText('To plan odtworzony z kopii.',{exact:true}).waitFor({timeout:45000});
    if(await page.getByText('Potwierdzone według zapisanych ustaleń',{exact:true}).count()) throw new Error('Imported backup retained confirmations');
    report.flows.push('Private JSON backup, deletion and import with consent reset');
    await page.getByRole('button',{name:/Zapisane plany/}).click();
    await page.getByRole('button',{name:'Bieżący plan',exact:true}).click();
    await page.getByRole('button',{name:'Usuń bieżący plan',exact:true}).click();
    await page.getByRole('button',{name:'Usuń plan i powiązane dane',exact:true}).click();
    await page.getByRole('dialog').waitFor({state:'hidden',timeout:30000});
    await page.getByRole('button',{name:/Katalog źródeł/}).click();
    await page.locator('.catalog-card').first().waitFor();
    if(await page.getByLabel('Zakres katalogu').inputValue()!=='verified') throw new Error('Verified catalog not selected');
    const enrollmentCard=page.locator('.catalog-card').filter({has:page.getByRole('heading',{name:/KIDS SPACE.*Barska/i})});
    await enrollmentCard.waitFor({timeout:30000});
    const enrollmentFacts=(await enrollmentCard.locator('.source-list').innerText()).replace(/\s+/g,' ');
    if(!/500,00\s*zł/.test(enrollmentFacts)||!enrollmentFacts.includes('Wpisowe / rekrutacja')||!enrollmentFacts.includes('Jednorazowo')) throw new Error('Public catalog enrollment amount lost its component or period');
    if(!(await enrollmentCard.innerText()).includes('Pozostałe opłaty wymagają osobnego potwierdzenia')) throw new Error('Component amount appears without remaining-cost qualification');
    const enrollmentMissing=await enrollmentCard.locator('.missing-fields').innerText();
    for(const label of ['Koszt bieżącej opieki','Koszt wyżywienia','Przyjęcie konkretnej osoby']) if(!enrollmentMissing.includes(label)) throw new Error('Public catalog fails to identify missing confirmation: '+label);
    report.catalog_price_component={record:'KIDS SPACE Barska',amount_grosze:50000,component:'enrollment',period:'once',displayed_facts:enrollmentFacts,displayed_missing_fields:enrollmentMissing};
    await scan('verified-catalog');
    await page.screenshot({path:path.join(evidence,'catalog-desktop.png'),fullPage:true});
    report.flows.push('Real public catalog source with review date and missing data');
    report.flows.push('Public enrollment fee rendered as a one-time component, separately from ongoing care costs');
  } finally {
    fs.writeFileSync(path.join(evidence,'browser-report.json'),JSON.stringify(report,null,2));
    await context.close();
    if(process.env.RECORD_VIDEO) fs.writeFileSync(path.join(evidence,'demo-recording.webm'),fs.readFileSync(await page.video().path()));
    await browser.close();
  }
  if(errors.length) throw new Error(errors.join('\n'));
  if(consoleErrors.length) throw new Error(consoleErrors.join('\n'));
  if(report.responsive.some(r=>!r.passes)) throw new Error('Responsive/zoom overflow detected');
  if(report.axe.some(s=>s.violations.some(v=>['critical','serious'].includes(v.impact)))) throw new Error('Serious accessibility violations detected; see browser-report.json');
  console.log(JSON.stringify({flows:report.flows,axe:report.axe.map(s=>({screen:s.screen,violations:s.violations.map(v=>v.id)})),responsive:report.responsive,errors},null,2));
})().catch(error=>{console.error(error);process.exitCode=1});
