import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Check, Circle, Download, Eye, FileText, Handshake, LockKeyhole, MessageSquare, X } from 'lucide-react';
import { api, download } from './api';
import { dependenciesOf, titleOf } from './Results';
import { Badge, Button, Empty, Field, Modal, Notice, SectionTitle, formatDate } from './ui';
import type { AnyRecord, SavedPlan, Scenario } from './types';

export default function Agreements({scenario,result,alternative,plan,onSave,onDecision,onNext,busy,onError}:{scenario:Scenario;result:AnyRecord|null;alternative:AnyRecord|null;plan:SavedPlan|null;onSave:()=>void;onDecision:(data:AnyRecord)=>Promise<void>;onNext:()=>void;busy:boolean;onError:(message:string)=>void}) {
 const [recipient,setRecipient]=useState('employer');const [fields,setFields]=useState(['schedule','flexibility','trial_period']);const [preview,setPreview]=useState<AnyRecord|null>(null);const [pending,setPending]=useState(false);const [decision,setDecision]=useState<AnyRecord|null>(null);const [decisionType,setDecisionType]=useState('accepted');const [party,setParty]=useState('');const [until,setUntil]=useState(scenario.end_date);const [notes,setNotes]=useState('');const [counter,setCounter]=useState('08:30');
 const eventKinds=recipient==='employer'?['work']:recipient==='caregiver'?['care','travel']:['work','course','care','travel','obligation'];
 const [decisionError,setDecisionError]=useState('');const decisionErrorRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(decisionError&&decision){const frame=requestAnimationFrame(()=>decisionErrorRef.current?.focus());return()=>cancelAnimationFrame(frame)}},[decisionError,decision]);
 const deps=dependenciesOf(alternative);const confirmed=plan?.status==='confirmed'||plan?.status==='trial'||plan?.status==='completed';
 const prepare=async()=>{setPending(true);try{setPreview(await api('/api/export',{scenario,alternative_id:alternative?.id||null,recipient,event_kinds:eventKinds,format:'preview',approved_fields:fields,input_version:String(plan?.version??scenario.version),...(plan?{plan_id:plan.id}:{})}));}catch(e){onError((e as Error).message)}finally{setPending(false)}};
 const exportFile=async(format:string)=>{if(!preview)return;setPending(true);try{const file=await api('/api/export',{scenario,alternative_id:alternative?.id||null,recipient,event_kinds:eventKinds,format,approved_fields:fields,preview_id:preview.preview_id,input_version:String(plan?.version??scenario.version),...(plan?{plan_id:plan.id}:{})});download(file,`okno-karta.${format==='text'?'txt':format}`,format==='text'?'text/plain':'application/octet-stream')}catch(e){onError((e as Error).message)}finally{setPending(false)}};
 function openDecision(dep:AnyRecord,type:string){setDecisionError('');onError('');setDecision(dep);setDecisionType(type);setParty(dep.owner||'Pracodawca');setNotes('');setUntil(dep.valid_to||scenario.end_date)}
 const submitDecision=async()=>{if(!decision)return;setDecisionError('');try{await onDecision({dependency_id:decision.id,decision:decisionType,party,valid_until:until,notes,...(decisionType==='counterproposal'?{counterproposal_start:counter}:{})});setDecision(null);setPreview(null)}catch(e){setDecisionError((e as Error).message)}};
 if(!result)return <Empty title="Uzgodnienia zaczynają się od możliwości" action="Sprawdź plan" onAction={onNext}>Po obliczeniu wariantu przygotujesz kartę do rozmowy i zapiszesz odpowiedzi.</Empty>;
 return <div><SectionTitle eyebrow="03 / Od możliwości do ustalenia" title="Uzgodnij wybrany wariant" description={alternative?`Wybrany wariant: ${titleOf(alternative)}. Wybierz informacje do karty i sprawdź podgląd.`:'Możesz przygotować opis bariery dla doradcy.'}/><div className="agreement-layout"><div><section className="panel"><div className="row"><h3>Co trzeba uzgodnić</h3><Badge tone={confirmed?'green':'amber'}>{confirmed?'Potwierdzone według zapisanych ustaleń':'Oczekuje na ustalenia'}</Badge></div><p className="subtle">Zapisujesz otrzymaną odpowiedź. Okno nie wysyła wiadomości.</p>{!plan&&<Notice><strong>Zapisz plan, aby zachować odpowiedzi.</strong> Wrócisz do ustaleń w tej przeglądarce.<br/><button className="text-button" onClick={onSave}>Zapisz plan świadomie <ArrowRight size={15}/></button></Notice>}
 {!alternative?<Notice tone="warning">Nie ma obecnie wykonalnego wariantu do potwierdzenia. Odpowiedzi pozostają w historii. Popraw warunki lub pobierz opis bariery dla doradcy.</Notice>:deps.length===0?<Notice tone="success">Ten wariant nie wskazuje nowych zależności do uzgodnienia. Przed próbą ponownie sprawdzimy aktualność całego planu.</Notice>:<ol className="action-list">{deps.map((dep,i)=>{const saved=plan?.decisions?.filter(d=>d.dependency_id===dep.id).at(-1);const accepted=dep.confirmation==='accepted';return <li key={dep.id}><div className={`action-check ${accepted?'done':''}`}>{accepted?<Check size={17}/>:i+1}</div><div className="action-content"><div className="row"><h4>{dep.description||dep.label}</h4>{accepted&&<Badge tone="green">Zapisano zgodę</Badge>}{saved?.decision==='rejected'&&<Badge tone="terracotta">Odmowa</Badge>}</div><p>{dep.owner||'Osoba decydująca'} · potrzebne do {formatDate(dep.valid_from||scenario.start_date)}</p><p className="small">Zakres: {formatDate(dep.valid_from||scenario.start_date)} do {formatDate(dep.valid_to||scenario.end_date)}</p>{saved&&<p className="small">Ostatnia odpowiedź: {saved.decision==='accepted'?'akceptacja':saved.decision==='rejected'?'odmowa':'kontrpropozycja'} · {saved.party}</p>}<div className="action-buttons"><button disabled={!plan||busy} onClick={()=>openDecision(dep,'accepted')}><Check size={15}/>Akceptacja</button><button disabled={!plan||busy} onClick={()=>openDecision(dep,'rejected')}><X size={15}/>Odmowa</button>{dep.kind==='work_hours'||dep.kind==='schedule_change'||dep.kind==='activity_shift'||dep.kind==='schedule'||dep.kind==='work_shift'||dep.fields?.some((f:string)=>f.includes('activities'))?<button disabled={!plan||busy} onClick={()=>openDecision(dep,'counterproposal')}><MessageSquare size={15}/>Kontrpropozycja</button>:null}</div></div></li>})}</ol>}
 {(alternative?.actions||[]).length>0&&<details className="details"><summary>Dalsze kroki i ich kolejność</summary><ol>{alternative!.actions.map((a:AnyRecord)=><li key={a.id}><strong>{a.description}</strong><p>{a.owner} · termin {formatDate(a.deadline)}{a.depends_on?.length?` · po uzgodnieniu ${a.depends_on.join(', ')}`:''}</p></li>)}</ol></details>}</section>
 {plan?.decisions?.length? <section className="panel"><h3>Historia odpowiedzi</h3><p>Zmiana warunków może unieważnić przydatność dawnej zgody. Zachowujemy zapis historii.</p>{plan.decisions.map((d,i)=><div className="history-row" key={d.id||i}><Handshake size={18}/><div><strong>{d.party||'Osoba decydująca'}: {d.decision==='accepted'?'akceptacja':d.decision==='rejected'?'odmowa':'kontrpropozycja'}</strong><p>{d.notes||'Relacja użytkowniczki'} · ważność do {formatDate(d.valid_until)}</p></div><Badge>Zapis historyczny · {formatDate(d.recorded_at||d.created_at)}</Badge></div>)}</section>:null}
 {plan?.rejected_alternatives?.length?<section className="panel"><h3>Warianty wycofane po odmowie</h3><p>Odmowa wyklucza wskazane ustalenie. Obecne możliwości zostały obliczone ponownie.</p>{plan.rejected_alternatives.map((entry,i)=><details className="details" key={entry.decision_id||i}><summary>{titleOf(entry.alternative)} · wersja danych {entry.scenario_version}</summary><p>{entry.alternative.description||'Wariant historyczny. Nie jest aktualną propozycją.'}</p><ul>{(entry.alternative.changes||[]).map((change:AnyRecord,j:number)=><li key={j}>{change.message||change.description||`${change.from||''} → ${change.to||''}`}</li>)}</ul></details>)}</section>:null}
 <section className="privacy-card"><LockKeyhole size={23}/><div><h3>Karta pracodawcy bez danych rodziny</h3><p>Udostępnisz proponowane godziny i ustalenia dotyczące pracy. Dane opieki, prywatne notatki i koszty osobiste pozostają poza kartą.</p><p>Pobranie pliku nie wysyła go i nie potwierdza niczyjej zgody.</p></div></section></div>
 <section className="panel export-panel"><p className="eyebrow">Karta do rozmowy</p><h3>Sprawdź kartę przed pobraniem</h3><Field label="Dla kogo przygotowujesz kartę?"><select value={recipient} onChange={e=>{setRecipient(e.target.value);setPreview(null);setFields(e.target.value==='employer'?['schedule','flexibility','trial_period']:e.target.value==='caregiver'?['schedule','handoffs','trial_period']:['schedule','barriers','actions'])}}><option value="employer">Pracodawca</option><option value="caregiver">Inny opiekun</option><option value="advisor">Doradca</option></select></Field><fieldset className="check-group"><legend>Co ma zawierać karta</legend>{(recipient==='employer'?[['schedule','Proponowane godziny'],['flexibility','Dopuszczalna elastyczność'],['trial_period','Okres próby']]:recipient==='caregiver'?[['schedule','Wybrane godziny'],['handoffs','Przekazania opieki'],['trial_period','Okres próby']]:[['schedule','Proponowane godziny'],['barriers','Opis barier'],['actions','Potrzebne ustalenia'],['cost','Koszty w okresie']]).map(([key,label])=><label className="check" key={key}><input type="checkbox" checked={fields.includes(key)} onChange={e=>{setFields(e.target.checked?[...fields,key]:fields.filter(f=>f!==key));setPreview(null)}}/><span>{label}</span></label>)}</fieldset><Button onClick={prepare} disabled={pending||fields.length===0}><Eye size={17}/>{pending?'Przygotowuję…':'Zobacz dokładny podgląd'}</Button>{preview&&<div className="preview"><div className="row"><Badge tone="green"><Eye size={13}/>Podgląd odbiorcy</Badge><span className="small">Wersja {scenario.version}</span></div><iframe title="Dokładna treść karty odbiorcy" srcDoc={preview.html} sandbox="" className="preview-frame"/><details className="details"><summary><FileText size={15}/>Treść dostępna jako tekst</summary><pre className="preview-text">{preview.text}</pre></details><div className="download-buttons"><Button secondary disabled={pending} onClick={()=>exportFile('pdf')}><Download size={15}/>PDF</Button><Button secondary disabled={pending} onClick={()=>exportFile('html')}>HTML</Button><Button secondary disabled={pending} onClick={()=>exportFile('text')}>Tekst</Button></div><p className="small">Pliki zawierają tę samą zatwierdzoną wersję co podgląd. Zmiana danych lub zakresu wymaga nowego podglądu.</p></div>}</section></div>
 <div className="editor-footer"><p><Circle size={14}/>Po potwierdzeniu ustaleń rozpoczniesz próbę.</p><Button onClick={onNext}>Przejdź do próby<ArrowRight size={17}/></Button></div>
 <Modal open={!!decision} onOpenChange={v=>!v&&setDecision(null)} title={decisionType==='accepted'?'Zapisz akceptację':decisionType==='rejected'?'Zapisz odmowę':'Sprawdź kontrpropozycję'} description="Zapisujemy Twoją relację o odpowiedzi. Nie wysyłamy żadnych wiadomości.">{decisionError&&<div ref={decisionErrorRef} tabIndex={-1} role="alert" className="error-banner"><span>{decisionError}</span></div>}<p>{decision?.description}</p><div className="form-grid"><Field label="Kto podjął decyzję (rola)"><input value={party} onChange={e=>setParty(e.target.value)}/></Field><Field label="Odpowiedź obowiązuje do"><input type="date" value={until} onChange={e=>setUntil(e.target.value)}/></Field>{decisionType==='counterproposal'&&<Field label="Zaproponowany początek pracy"><input type="time" value={counter} onChange={e=>setCounter(e.target.value)}/></Field>}</div><Field label="Krótka notatka (opcjonalnie)"><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></Field>{decisionType==='counterproposal'&&<Notice>Nowa godzina utworzy kolejną wersję danych i zostanie sprawdzona razem z opieką oraz dojazdami.</Notice>}<Button onClick={submitDecision} disabled={busy||!party||!until}>{busy?'Zapisuję…':decisionType==='counterproposal'?'Zapisz i przelicz':'Zapisz odpowiedź'}</Button></Modal></div>;
}

