/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Examples */
        get: operations["examples_api_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solve */
        post: operations["solve_api_solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Routes */
        post: operations["routes_api_routes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_plans__plan_id__get"];
        put?: never;
        post?: never;
        /** Delete Plan */
        delete: operations["delete_plan_api_plans__plan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Version Plan */
        post: operations["version_plan_api_plans__plan_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decision Plan */
        post: operations["decision_plan_api_plans__plan_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/trial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Trial */
        post: operations["start_trial_api_plans__plan_id__trial_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Outcome */
        post: operations["add_outcome_api_plans__plan_id__outcomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/trial/repair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Repair Trial */
        post: operations["repair_trial_api_plans__plan_id__trial_repair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backup */
        get: operations["backup_api_plans__plan_id__backup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Backup */
        post: operations["import_backup_api_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /** Weekdays */
            weekdays?: number[];
            /** Dates */
            dates?: string[];
            /** Excluded Dates */
            excluded_dates?: string[];
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @default work
             * @enum {string}
             */
            kind: "work" | "course" | "obligation";
            /**
             * Location
             * @default work
             */
            location: string;
            /**
             * Start
             * @default 09:00
             */
            start: string | null;
            /** Start Fold */
            start_fold?: number | null;
            /**
             * Duration Minutes
             * @default 480
             */
            duration_minutes: number;
            /**
             * Paid Minutes
             * @default 480
             */
            paid_minutes: number;
            /**
             * Negotiable
             * @default false
             */
            negotiable: boolean;
            /** Start Min */
            start_min?: string | null;
            /** Start Max */
            start_max?: string | null;
            /**
             * Step Minutes
             * @default 15
             */
            step_minutes: number;
            /** Agreement Id */
            agreement_id?: string | null;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /** Offer Group */
            offer_group?: string | null;
            /** Requires Activity Ids */
            requires_activity_ids?: string[];
            /**
             * Cost Grosze
             * @default 0
             */
            cost_grosze: number | null;
            /**
             * Cost Frequency
             * @default once
             * @enum {string}
             */
            cost_frequency: "once" | "occurrence";
            source?: components["schemas"]["Source"];
        };
        /** Availability */
        Availability: {
            /** Weekdays */
            weekdays?: number[];
            /** Dates */
            dates?: string[];
            /** Excluded Dates */
            excluded_dates?: string[];
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Start
             * @default 07:00
             */
            start: string | null;
            /**
             * End
             * @default 17:00
             */
            end: string | null;
            /** Start Fold */
            start_fold?: number | null;
            /** End Fold */
            end_fold?: number | null;
        };
        /** Baseline */
        Baseline: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Worked Minutes */
            worked_minutes?: number | null;
            /** Cost Grosz */
            cost_grosz?: number | null;
            /** Organization Minutes */
            organization_minutes?: number | null;
        };
        /** CalendarRule */
        CalendarRule: {
            /** Weekdays */
            weekdays?: number[];
            /** Dates */
            dates?: string[];
            /** Excluded Dates */
            excluded_dates?: string[];
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** CareArrangement */
        CareArrangement: {
            /** Id */
            id: string;
            /** Resource Ids */
            resource_ids: string[];
            /** Handoffs */
            handoffs?: components["schemas"]["CareHandoff"][];
            /** Unavailable */
            unavailable?: components["schemas"]["CalendarRule"][];
        };
        /** CareHandoff */
        CareHandoff: {
            /** At */
            at: string;
            /** At Fold */
            at_fold?: number | null;
            /** By Resource Id */
            by_resource_id: string;
            /** Leg Id */
            leg_id?: string | null;
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /** Valid To */
            valid_to?: string | null;
            source?: components["schemas"]["Source"];
        };
        /** CareNeed */
        CareNeed: {
            /** Weekdays */
            weekdays?: number[];
            /** Dates */
            dates?: string[];
            /** Excluded Dates */
            excluded_dates?: string[];
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Id */
            id: string;
            /** Dependent Id */
            dependent_id: string;
            /** Label */
            label: string;
            /**
             * Care Type
             * @default child
             */
            care_type: string;
            /**
             * Start
             * @default 00:00
             */
            start: string | null;
            /**
             * End
             * @default 24:00
             */
            end: string | null;
            /** Start Fold */
            start_fold?: number | null;
            /** End Fold */
            end_fold?: number | null;
            /**
             * Allow Self Care
             * @default true
             */
            allow_self_care: boolean;
            /** Resource Ids */
            resource_ids?: string[];
            /**
             * Visit Order
             * @default 0
             */
            visit_order: number;
            /** Arrangements */
            arrangements?: components["schemas"]["CareArrangement"][];
        };
        /** CareResource */
        CareResource: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Location */
            location: string;
            /**
             * Kind
             * @default facility
             * @enum {string}
             */
            kind: "facility" | "caregiver" | "service";
            /**
             * Capacity
             * @default 1
             */
            capacity: number;
            /** Dependent Ids */
            dependent_ids?: string[];
            /** Care Types */
            care_types?: string[];
            /** Availability */
            availability?: components["schemas"]["Availability"][];
            /** Busy */
            busy?: components["schemas"]["Availability"][];
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /**
             * Negotiable
             * @default true
             */
            negotiable: boolean;
            /** Confirmation Valid To */
            confirmation_valid_to?: string | null;
            /**
             * Daily Cost Grosze
             * @default 0
             */
            daily_cost_grosze: number | null;
            /**
             * Hourly Cost Grosze
             * @default 0
             */
            hourly_cost_grosze: number | null;
            /**
             * One Time Cost Grosze
             * @default 0
             */
            one_time_cost_grosze: number | null;
            source?: components["schemas"]["Source"];
        };
        /** Coordinate */
        Coordinate: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Expected Version */
            expected_version: number;
            /** Dependency Id */
            dependency_id: string;
            /** Alternative Id */
            alternative_id?: string | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "accepted" | "rejected" | "counterproposal";
            /** Party */
            party: string;
            /**
             * Valid Until
             * Format: date
             */
            valid_until: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Counterproposal Start */
            counterproposal_start?: string | null;
            /**
             * Source
             * @default self_report
             * @constant
             */
            source: "self_report";
        };
        /** ExportRequest */
        ExportRequest: {
            scenario: components["schemas"]["Scenario"];
            /** Alternative Id */
            alternative_id?: string | null;
            /**
             * Recipient
             * @default employer
             * @enum {string}
             */
            recipient: "employer" | "caregiver" | "advisor" | "personal";
            /**
             * Format
             * @default preview
             * @enum {string}
             */
            format: "preview" | "html" | "text" | "pdf" | "ics";
            /** Approved Fields */
            approved_fields?: string[];
            /** Preview Id */
            preview_id?: string | null;
            /**
             * Input Version
             * @default 1
             */
            input_version: string | number;
            /** Plan Id */
            plan_id?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Event Kinds */
            event_kinds?: ("work" | "course" | "care" | "travel" | "obligation")[];
        };
        /** ForbiddenProposal */
        ForbiddenProposal: {
            /** Activity Id */
            activity_id: string;
            /** Start */
            start: string;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Reason
             * @default Odmowa zmiany godzin
             */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            /** Backup */
            backup: {
                [key: string]: unknown;
            };
        };
        /** OutcomeRequest */
        OutcomeRequest: {
            /** Expected Version */
            expected_version: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Worked Minutes */
            worked_minutes?: number | null;
            /** Cost Grosz */
            cost_grosz?: number | null;
            /** Organization Minutes */
            organization_minutes?: number | null;
            /**
             * Disruptions
             * @default
             */
            disruptions: string;
            /**
             * Source
             * @default self_report
             * @constant
             */
            source: "self_report";
            /**
             * Complete Trial
             * @default false
             */
            complete_trial: boolean;
        };
        /** Point */
        Point: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** RepairTrialRequest */
        RepairTrialRequest: {
            /** Expected Version */
            expected_version: number;
            /** Alternative Id */
            alternative_id: string;
        };
        /** RouteQuery */
        RouteQuery: {
            /**
             * Id
             * @default route
             */
            id: string;
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /**
             * When
             * Format: date-time
             */
            when: string;
            /**
             * Arrive By
             * @default false
             */
            arrive_by: boolean;
            /**
             * Mode
             * @default manual
             * @enum {string}
             */
            mode: "manual" | "walk" | "transit";
            from_point?: components["schemas"]["Point"] | null;
            to_point?: components["schemas"]["Point"] | null;
            manual_leg?: components["schemas"]["TravelLeg"] | null;
            /**
             * Handoff Minutes
             * @default 0
             */
            handoff_minutes: number;
            /**
             * Buffer Minutes
             * @default 0
             */
            buffer_minutes: number;
            /**
             * Access Minutes
             * @default 0
             */
            access_minutes: number;
            /** Cost Grosze */
            cost_grosze?: number | null;
        };
        /** RoutesRequest */
        RoutesRequest: {
            /** Queries */
            queries: components["schemas"]["RouteQuery"][];
        };
        /** SaveRequest */
        SaveRequest: {
            scenario: components["schemas"]["Scenario"];
            /** Selected Alternative Id */
            selected_alternative_id?: string | null;
        };
        /** Scenario */
        Scenario: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Title
             * @default Mój plan
             */
            title: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /**
             * Data Mode
             * @default personal
             * @enum {string}
             */
            data_mode: "synthetic" | "personal";
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Timezone
             * @default Europe/Warsaw
             * @constant
             */
            timezone: "Europe/Warsaw";
            /**
             * Home Location
             * @default home
             */
            home_location: string;
            /** Location Coordinates */
            location_coordinates?: {
                [key: string]: components["schemas"]["Coordinate"];
            };
            /**
             * Self Care Capacity
             * @default 1
             */
            self_care_capacity: number;
            /** Activities */
            activities: components["schemas"]["Activity"][];
            /** Care Needs */
            care_needs?: components["schemas"]["CareNeed"][];
            /** Care Resources */
            care_resources?: components["schemas"]["CareResource"][];
            /** Travel Legs */
            travel_legs?: components["schemas"]["TravelLeg"][];
            /** Budget Grosze */
            budget_grosze?: number | null;
            /**
             * Minimum Paid Minutes
             * @default 0
             */
            minimum_paid_minutes: number;
            /**
             * Minimum Rest Minutes
             * @default 660
             */
            minimum_rest_minutes: number;
            /**
             * Preferred Extra Buffer Minutes
             * @default 15
             */
            preferred_extra_buffer_minutes: number;
            /** Objective Order */
            objective_order?: ("changed_agreements" | "shift_minutes" | "cost_grosze")[];
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Forbidden Proposals */
            forbidden_proposals?: components["schemas"]["ForbiddenProposal"][];
        };
        /** Source */
        Source: {
            /**
             * Label
             * @default deklaracja użytkowniczki
             */
            label: string;
            /** Url */
            url?: string | null;
            /** Checked At */
            checked_at?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Status
             * @default current
             * @enum {string}
             */
            status: "current" | "stale" | "unknown";
        };
        /** TravelBand */
        TravelBand: {
            /** Weekdays */
            weekdays?: number[];
            /** Dates */
            dates?: string[];
            /** Excluded Dates */
            excluded_dates?: string[];
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Start
             * @default 00:00
             */
            start: string;
            /**
             * End
             * @default 24:00
             */
            end: string;
            /** Minutes */
            minutes?: number | null;
            /**
             * Cost Grosze
             * @default 0
             */
            cost_grosze: number | null;
        };
        /** TravelLeg */
        TravelLeg: {
            /** Id */
            id: string;
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /**
             * Mode
             * @default manual
             * @enum {string}
             */
            mode: "manual" | "walk" | "transit" | "bike" | "car";
            /** Bands */
            bands: components["schemas"]["TravelBand"][];
            /**
             * Handoff Minutes
             * @default 0
             */
            handoff_minutes: number;
            /**
             * Buffer Minutes
             * @default 0
             */
            buffer_minutes: number;
            /**
             * Access Minutes
             * @default 0
             */
            access_minutes: number;
            source?: components["schemas"]["Source"];
        };
        /** TrialRequest */
        TrialRequest: {
            /** Expected Version */
            expected_version: number;
            /** Alternative Id */
            alternative_id: string;
            baseline: components["schemas"]["Baseline"];
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionRequest */
        VersionRequest: {
            scenario: components["schemas"]["Scenario"];
            /** Selected Alternative Id */
            selected_alternative_id?: string | null;
            /** Expected Version */
            expected_version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    examples_api_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    catalog_api_catalog_get: {
        parameters: {
            query?: {
                mode?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_api_solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Scenario"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    routes_api_routes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plan_api_plans__plan_id__delete: {
        parameters: {
            query: {
                expected_version: number;
            };
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_plan_api_plans__plan_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_plan_api_plans__plan_id__decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_trial_api_plans__plan_id__trial_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_outcome_api_plans__plan_id__outcomes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repair_trial_api_plans__plan_id__trial_repair_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepairTrialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backup_api_plans__plan_id__backup_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_backup_api_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
