import { useEffect, useRef, useState } from 'react';
import { ArrowRight, BookOpen, CalendarDays, Check, ChevronDown, CircleHelp, Download, FolderOpen, HeartHandshake, LayoutGrid, Leaf, LoaderCircle, Menu, Plus, Save, ShieldCheck, Sparkles, Trash2, Upload, X } from 'lucide-react';
import { ApiValidationError, api, download, setCsrf } from './api';
import type { InputIssue } from './api';
import { blankScenario, normalizeExample, normalizeScenario } from './types';
import type { AnyRecord, SavedPlan, Scenario } from './types';
import { Button, Modal, Notice, formatDate } from './ui';
import Editor, { validateScenarioInputs } from './Editor';
import Results, { alternativesOf } from './Results';
import Agreements from './Agreements';
import Trial from './Trial';
import Catalog from './Catalog';

const steps=[{id:'plan',label:'Twój plan',note:'Godziny i granice',icon:CalendarDays},{id:'results',label:'Twoje możliwości',note:'Konflikt i warianty',icon:LayoutGrid},{id:'agreements',label:'Uzgodnienia',note:'Karta i odpowiedzi',icon:HeartHandshake},{id:'trial',label:'Próba i wynik',note:'Sprawdź w codzienności',icon:Leaf}];
function App(){
 const [scenario,setScenario]=useState<Scenario>(blankScenario);const [result,setResult]=useState<AnyRecord|null>(null);const [plan,setPlan]=useState<SavedPlan|null>(null);const [selectedId,setSelectedId]=useState<string|null>(null);const [page,setPage]=useState('plan');const [examples,setExamples]=useState<AnyRecord[]>([]);const [saved,setSaved]=useState<AnyRecord[]>([]);const [catalog,setCatalog]=useState<AnyRecord|null>(null);const [catalogMode,setCatalogMode]=useState<'verified'|'synthetic'|'all'>('verified');const [catalogBusy,setCatalogBusy]=useState(true);const [catalogRefresh,setCatalogRefresh]=useState(0);const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [dirty,setDirty]=useState(false);const [modal,setModal]=useState<string|null>(null);const [navOpen,setNavOpen]=useState(false);const [saveConsent,setSaveConsent]=useState(false);const [retention,setRetention]=useState(30);const [pendingExample,setPendingExample]=useState<AnyRecord|null>(null);const [routingMode,setRoutingMode]=useState('manual');const generation=useRef(0);const importInput=useRef<HTMLInputElement>(null);const mainHeading=useRef<HTMLHeadingElement>(null);
 const alternative=alternativesOf(result).find(a=>a.id===selectedId)||alternativesOf(result)[0]||null;
 const [inputIssues,setInputIssues]=useState<InputIssue[]>([]);const [validationAttempt,setValidationAttempt]=useState(0);
 const errorRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(error&&modal){const frame=requestAnimationFrame(()=>errorRef.current?.focus());return()=>cancelAnimationFrame(frame)}},[error,modal]);
 function dismissError(){const dialog=errorRef.current?.closest('[role="dialog"]');setError('');requestAnimationFrame(()=>{if(dialog)dialog.querySelector<HTMLButtonElement>('button:not([disabled])')?.focus();else mainHeading.current?.focus()})}
 const [mobileNav,setMobileNav]=useState(()=>window.matchMedia('(max-width:760px)').matches);const sidebarRef=useRef<HTMLElement>(null);const menuButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const media=window.matchMedia('(max-width:760px)');const changed=()=>{const active=document.activeElement;const inSidebar=sidebarRef.current?.contains(active);setMobileNav(media.matches);setNavOpen(false);if(media.matches&&inSidebar)requestAnimationFrame(()=>menuButton.current?.focus());else if(!media.matches&&(active===menuButton.current||active?.classList.contains('mobile-nav-close')))requestAnimationFrame(()=>sidebarRef.current?.querySelector<HTMLButtonElement>('.nav-item')?.focus())};media.addEventListener('change',changed);return()=>media.removeEventListener('change',changed)},[]);
 useEffect(()=>{if(mobileNav&&navOpen){const frame=requestAnimationFrame(()=>sidebarRef.current?.querySelector<HTMLButtonElement>('.mobile-nav-close')?.focus());return()=>cancelAnimationFrame(frame)}},[mobileNav,navOpen]);
 function closeNavigation(restoreFocus=true){setNavOpen(false);if(restoreFocus)requestAnimationFrame(()=>menuButton.current?.focus())}
 function openNavModal(next:string){if(mobileNav&&navOpen){setNavOpen(false);requestAnimationFrame(()=>{menuButton.current?.focus();setModal(next)})}else setModal(next)}
 function navKeys(event:React.KeyboardEvent<HTMLElement>){
  if(!mobileNav||!navOpen)return;
  if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeNavigation();return}
  if(event.key==='Tab'){const items=Array.from(sidebarRef.current?.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),[tabindex="0"]')||[]).filter(item=>item.getClientRects().length>0);const first=items[0];const last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}
 }
 const refreshSession=async()=>{const session=await api('/api/session');setCsrf(session.csrf_token);setSaved(session.saved_plans||[]);setRetention(session.retention_days||30);setRoutingMode(session.routing_mode||'manual');setReady(true)};
 useEffect(()=>{let active=true;Promise.allSettled([api('/api/session'),api('/api/examples')]).then(res=>{if(!active)return;if(res[0].status==='fulfilled'){setCsrf(res[0].value.csrf_token);setSaved(res[0].value.saved_plans||[]);setRetention(res[0].value.retention_days||30);setRoutingMode(res[0].value.routing_mode||'manual');setReady(true)}else setError('Nie udało się połączyć z aplikacją. Formularz jest dostępny, a dane pozostają w pamięci przeglądarki. Odśwież połączenie przed analizą.');if(res[1].status==='fulfilled')setExamples(res[1].value.items||[])});return()=>{active=false;generation.current++}},[]);
 useEffect(()=>{let active=true;setCatalogBusy(true);setCatalog(null);api(`/api/catalog?mode=${catalogMode}`).then(data=>{if(active)setCatalog(data)}).catch(e=>{if(active)setError((e as Error).message)}).finally(()=>{if(active)setCatalogBusy(false)});return()=>{active=false}},[catalogMode,catalogRefresh]);
 function navigate(next:string){setPage(next);setNavOpen(false);window.scrollTo({top:0,behavior:'instant'});requestAnimationFrame(()=>mainHeading.current?.focus())}
 function updateScenario(next:Scenario){generation.current++;setInputIssues(previous=>previous.length?validateScenarioInputs(next):previous);setScenario({...next,version:scenario.version+1});setResult(null);setSelectedId(null);setDirty(true);setMessage('Dane zmienione. Przelicz plan, aby sprawdzić aktualne możliwości.');setError('')}
 function loadPlan(p:SavedPlan){generation.current++;setInputIssues([]);setPlan(p);setScenario(normalizeScenario(p.scenario));setResult(p.result);setSelectedId(p.selected_alternative_id||alternativesOf(p.result)[0]?.id||null);setDirty(false)}
 function reset(example:AnyRecord|null){generation.current++;setInputIssues([]);setScenario(example?normalizeExample(example.scenario):blankScenario());setPlan(null);setResult(null);setSelectedId(null);setDirty(false);setModal(null);setMessage(example?'Wczytano przykład syntetyczny. Sprawdź plan, aby zobaczyć wynik obliczeń.':'Nowy formularz jest gotowy.');setError('');navigate('plan')}
 function requestReset(example:AnyRecord|null){if(dirty||scenario.activities.length){setPendingExample(example);setModal('reset')}else reset(example)}
 const solve=async()=>{setError('');const issues=validateScenarioInputs(scenario);if(issues.length){setInputIssues(issues);setValidationAttempt(value=>value+1);setPage('plan');setNavOpen(false);return}setInputIssues([]);setBusy(true);const current=++generation.current;try{if(!ready)await refreshSession();const next=await api('/api/solve',scenario);if(generation.current!==current)return;setResult(next);setSelectedId(next.alternatives?.[0]?.id||null);setMessage('Analiza gotowa. Porównaj warianty i wybierz kolejny krok.');navigate('results')}catch(e){if(generation.current===current){if(e instanceof ApiValidationError){setInputIssues(e.issues);setValidationAttempt(value=>value+1);setPage('plan');setNavOpen(false)}else setError((e as Error).message)}}finally{setBusy(false)}};
 const save=async()=>{setBusy(true);setError('');const current=++generation.current;try{if(!ready)await refreshSession();const payload={scenario,selected_alternative_id:selectedId};const next=await api<SavedPlan>(plan?`/api/plans/${plan.id}/versions`:'/api/plans',plan?{...payload,expected_version:plan.version}:payload);if(current!==generation.current)return;loadPlan(next);setModal(null);setSaveConsent(false);setMessage(`Zapisano plan. Wersja ${next.version}.`);await refreshSession()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const openSaved=async(id:string)=>{setBusy(true);setError('');try{const p=await api<SavedPlan>(`/api/plans/${id}`);loadPlan(p);setModal(null);navigate(p.result?'results':'plan');setMessage('Wczytano aktualną wersję planu.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const mutation=async(path:string,data:AnyRecord)=>{if(!plan)throw new Error('Najpierw zapisz plan.');if(dirty)throw new Error('Dane zmieniły się. Zapisz nową wersję planu przed zapisaniem odpowiedzi.');setBusy(true);setError('');const current=++generation.current;try{const p=await api<SavedPlan>(`/api/plans/${plan.id}/${path}`,{...data,expected_version:plan.version,...(path==='decisions'?{alternative_id:alternative?.id}:{})});if(current!==generation.current)return;loadPlan(p);setMessage(path==='decisions'?'Zapisano odpowiedź i ponownie sprawdzono plan.':path==='trial'?'Rozpoczęto próbę według zapisanych ustaleń.':path==='trial/repair'?'Ponownie sprawdzono warunki i wznowiono próbę. Historia została zachowana.':'Zapisano rzeczywistą obserwację.');await refreshSession()}finally{setBusy(false)}};
 const backup=async()=>{if(!plan)return;setError('');try{download(await api(`/api/plans/${plan.id}/backup`),'okno-kopia-wlasna.json');setMessage('Pobrano prywatną kopię. Przechowuj ją w bezpiecznym miejscu.')}catch(e){setError((e as Error).message)}};
 const importBackup=async(file:File|undefined)=>{if(!file)return;setError('');setBusy(true);try{if(file.size>2_000_000)throw new Error('Kopia jest większa niż dozwolone 2 MB.');const parsed=JSON.parse(await file.text());const p=await api<SavedPlan>('/api/import',{backup:parsed});loadPlan(p);setModal(null);navigate('agreements');setMessage('Wczytano kopię jako nowy plan. Dawne ustalenia wymagają ponownej oceny.');await refreshSession()}catch(e){setError((e as Error).message)}finally{setBusy(false);if(importInput.current)importInput.current.value=''}};
 const deletePlan=async()=>{if(!plan)return;setError('');setBusy(true);generation.current++;try{await api(`/api/plans/${plan.id}?expected_version=${plan.version}`,undefined,{method:'DELETE'});reset(null);setMessage('Plan i powiązane dane zostały usunięte z aplikacji. Pobrane wcześniej pliki pozostają u ich posiadaczy.');await refreshSession()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const currentStep=steps.find(s=>s.id===page);const saveClick=()=>{setError('');setSaveConsent(false);setModal('save')};
 const errorAlert=error?<div ref={errorRef} tabIndex={-1} role="alert" className="error-banner"><span>{error}</span><button className="icon-button" aria-label="Zamknij komunikat błędu" onClick={dismissError}><X size={18}/></button></div>:null;
 return <div className="app-shell"><a className="skip-link" href="#main-content">Przejdź do treści</a><aside id="app-navigation" ref={sidebarRef} className={`sidebar ${navOpen?'open':''}`} role={mobileNav?'dialog':undefined} aria-label={mobileNav?'Menu nawigacji':undefined} aria-modal={mobileNav&&navOpen?true:undefined} aria-hidden={mobileNav&&!navOpen?true:undefined} inert={mobileNav&&!navOpen} onKeyDown={navKeys}><button className="icon-button mobile-nav-close" aria-label="Zamknij menu nawigacji" onClick={()=>closeNavigation()}><X size={21}/></button><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('plan')}} aria-label="Okno, Twój plan"><span className="brand-symbol"><i/><i/><i/><i/></span><span>okno<span className="brand-period">.</span></span></a><p className="brand-tagline">Praca, opieka i dojazdy.</p><div className="sidebar-label">TWÓJ KOLEJNY KROK</div><nav aria-label="Główna nawigacja">{steps.map((s,i)=><button key={s.id} className={`nav-item ${page===s.id?'active':''}`} onClick={()=>navigate(s.id)} aria-current={page===s.id?'step':undefined}><span className="nav-icon"><s.icon size={20}/></span><span><strong>{s.label}</strong><small>{s.note}</small></span><span className="step-number">{i+1}</span></button>)}</nav><div className="sidebar-divider"/><button className={`nav-item ${page==='catalog'?'active':''}`} onClick={()=>navigate('catalog')}><span className="nav-icon"><BookOpen size={19}/></span><span><strong>Katalog źródeł</strong><small>Dane i ich aktualność</small></span></button><button className="nav-item" onClick={()=>openNavModal('saved')}><span className="nav-icon"><FolderOpen size={19}/></span><span><strong>Zapisane plany</strong><small>{saved.length?saved.length+' w tej przeglądarce':'Wróć do swoich ustaleń'}</small></span></button><div className="sidebar-bottom"><div className="sidebar-note"><span className="tiny-window" aria-hidden/><p>Wskaż godziny pracy i opieki.<br/><strong>Porównaj wykonalne warianty.</strong></p></div><button className="help-link" onClick={()=>openNavModal('privacy')}><ShieldCheck size={16}/>Prywatność i zapis danych</button><span className="version-label">Okno · ImpactHer 2026</span></div></aside>{mobileNav&&navOpen&&<button className="nav-backdrop" aria-label="Zamknij menu" aria-hidden="true" tabIndex={-1} onClick={()=>closeNavigation()}/>}
 <div className="main-shell" inert={mobileNav&&navOpen}><header className="topbar"><button ref={menuButton} className="icon-button mobile-menu" aria-label={navOpen?'Zamknij menu':'Otwórz menu'} aria-expanded={navOpen} aria-controls="app-navigation" aria-haspopup="dialog" onClick={()=>navOpen?closeNavigation():setNavOpen(true)}><Menu size={23}/></button><div className="breadcrumb">Twoja przestrzeń<span>/</span><strong>{currentStep?.label||'Katalog źródeł'}</strong></div><div className="topbar-actions"><span className="session-status"><span className={`dot ${plan?'forest':'neutral'}`}/>{plan?`Zapisany · wersja ${plan.version}${dirty?' · zmieniony':''}`:'Bez zapisu'}</span><Button secondary disabled={busy} onClick={saveClick}><Save size={16}/><span>{plan?'Zapisz wersję':'Zapisz plan'}</span></Button></div></header>
 <main id="main-content" className="main-content"><div className="page-heading"><div><p className="eyebrow">PRACA · OPIEKA · TWÓJ CZAS</p><h1 ref={mainHeading} tabIndex={-1}>{page==='plan'?<>Sprawdź, co zmienić,<br/><span>by wrócić do pracy.</span></>:page==='results'?'Zobacz konflikt. Porównaj warianty.':page==='agreements'?'Przygotuj godziny do rozmowy.':page==='trial'?'Sprawdź plan w codzienności.':'Sprawdź źródła i warunki.'}</h1>{page==='plan'&&<p className="lead">Sprawdź razem godziny pracy, opieki i dojazdów.<br className="desktop-break"/> Porównaj warianty i przygotuj konkretną propozycję dla pracodawcy.</p>}</div>{page==='plan'&&<div className="hero-note"><span className="note-asterisk">✳</span><p>Zachowaj wymagany<br/><strong>wymiar pracy.</strong></p></div>}</div>
 {!modal&&errorAlert}<div className="sr-only" role="status" aria-live="polite">{message}{busy?' Trwa przetwarzanie.':''}</div>{message&&<div className="message-bar"><Check size={16}/><span>{message}</span><button className="icon-button" aria-label="Ukryj informację" onClick={()=>setMessage('')}><X size={15}/></button></div>}
 {(plan as AnyRecord)?.restored_history&&<Notice tone="warning"><strong>To plan odtworzony z kopii.</strong> Dawne dane i obserwacje są historią. Sprawdź ponownie ważność źródeł pracy, opieki i dojazdów oraz potwierdź potrzebne ustalenia. <button className="text-button" onClick={()=>setModal('manage')}>Zobacz zachowaną historię</button></Notice>}{page==='plan'&&<><div className="start-options"><div><Sparkles size={18}/><span>Zobacz, jak usunąć konflikt 45 minut</span></div><div className="row"><select aria-label="Wybierz przykład syntetyczny" value="" disabled={busy} onChange={e=>{const example=examples.find(x=>x.id===e.target.value);if(example)requestReset(example)}}><option value="">Otwórz przykład</option>{examples.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select><button className="text-button" disabled={busy} onClick={()=>requestReset(null)}><Plus size={16}/>Własny plan</button></div></div>{scenario.data_mode==='synthetic'&&<Notice tone="warning"><strong>Przykład syntetyczny: {scenario.title}.</strong> Dane i wyniki demonstracyjne. <button className="text-button" onClick={()=>requestReset(null)}>Zacznij z własnymi danymi <ArrowRight size={14}/></button></Notice>}<Editor scenario={scenario} onChange={updateScenario} onSolve={solve} busy={busy} inputIssues={inputIssues} validationAttempt={validationAttempt}/></>}
 {page==='results'&&<Results scenario={scenario} result={result} selectedId={selectedId} onSelect={id=>{setSelectedId(id);if(plan)setDirty(true)}} onEdit={()=>navigate('plan')} onNext={()=>navigate('agreements')} onSolve={solve} busy={busy}/>}
 {page==='agreements'&&<Agreements key={`${scenario.version}-${plan?.version||0}-${selectedId}`} scenario={scenario} result={result} alternative={alternative} plan={dirty?null:plan} onSave={saveClick} onDecision={data=>mutation('decisions',data)} onNext={()=>navigate(result?'trial':'plan')} busy={busy} onError={setError}/>}
 {page==='trial'&&<Trial key={`${plan?.id||'draft'}-${scenario.version}`} scenario={scenario} alternative={alternative} plan={plan} dirty={dirty} onSave={saveClick} onRepair={data=>mutation('trial/repair',data)} onTrial={data=>mutation('trial',data)} onOutcome={data=>mutation('outcomes',data)} onBack={()=>navigate(result?'agreements':'plan')} busy={busy} onError={setError}/>}
 {page==='catalog'&&<Catalog catalog={catalog} mode={catalogMode} onModeChange={setCatalogMode} busy={catalogBusy} onRefresh={()=>setCatalogRefresh(value=>value+1)}/>}
 <footer className="footer"><span><span className="footer-brand">okno.</span> Praca, opieka i dojazdy w jednym planie.</span><button onClick={()=>setModal('privacy')}>Jak chronimy Twoje dane <ArrowRight size={13}/></button></footer></main></div>
 {busy&&<div className="busy-indicator" role="status"><LoaderCircle className="spin" size={18}/>Trwa przetwarzanie…</div>}
 <Modal open={modal==='save'} onOpenChange={v=>!v&&setModal(null)} title={plan?'Zapisz nową wersję planu':'Chcesz wrócić do swojego planu?'} description="Zapis na serwerze jest osobną, dobrowolną decyzją.">{errorAlert}<Notice><strong>Dostęp jest przypisany do tej przeglądarki.</strong> Usunięcie jej cookie może oznaczać utratę dostępu. Po zapisie pobierz własną kopię JSON.</Notice><p>Plan zostanie zachowany na serwerze. Domyślny okres bez aktywności to {retention} dni. Zmiany powiązanych warunków wymagają ponownego sprawdzenia dawnych ustaleń.</p><label className="check"><input type="checkbox" checked={saveConsent} onChange={e=>setSaveConsent(e.target.checked)}/><span>Chcę zapisać te dane i rozumiem sposób dostępu.</span></label><Button disabled={busy||!saveConsent} onClick={save}><Save size={16}/>{plan?'Zapisz nową wersję':'Zapisz mój plan'}</Button></Modal>
 <Modal open={modal==='saved'} onOpenChange={v=>!v&&setModal(null)} title="Twoje zapisane plany" description="Lista obejmuje tylko plany dostępne w obecnej sesji przeglądarki.">{errorAlert}{saved.length===0?<p>Nie masz jeszcze zapisanych planów. Możesz pracować bez zapisu albo zaimportować własną kopię.</p>:saved.map(p=><button className="saved-plan" key={p.id} disabled={busy} onClick={()=>openSaved(p.id)}><FolderOpen size={20}/><span><strong>{p.title}</strong><small>Wersja {p.version} · {formatDate(p.updated_at)}</small></span><ArrowRight size={17}/></button>)}<div className="modal-actions"><Button secondary disabled={busy} onClick={()=>importInput.current?.click()}><Upload size={16}/>Importuj kopię JSON</Button>{plan&&<Button secondary onClick={()=>setModal('manage')}><ChevronDown size={16}/>Bieżący plan</Button>}</div><p className="small">Import tworzy nowy plan. Dawne zgody pozostają historią do ponownej oceny.</p></Modal>
 <Modal open={modal==='manage'} onOpenChange={v=>!v&&setModal(null)} title="Kopia, historia i usunięcie" description={plan?`Bieżący plan: ${plan.scenario.title}`:'Nie ma zapisanego planu.'}>{errorAlert}<Button secondary onClick={backup}><Download size={16}/>Pobierz własną kopię JSON</Button><p className="small">Ta kopia zawiera Twoje prywatne dane. Nie jest kartą dla pracodawcy.</p><h3>Historia wersji</h3>{(plan as AnyRecord)?.restored_history&&<details className="details"><summary>Historia z odtworzonej kopii</summary><p>Te obserwacje nie są wynikiem nowego planu i nie stanowią aktualnych zgód.</p><pre className="preview-text">{JSON.stringify((plan as AnyRecord).restored_history,null,2)}</pre></details>}<div className="version-history">{plan?.versions?.map((v,i)=><details className="details" key={i}><summary>Wersja {v.version} · {formatDate(v.created_at)}</summary><p>{v.scenario?.title||'Zapis warunków planu'}</p><p>{v.scenario?.activities?.length||0} zajęć · {v.scenario?.care_resources?.length||0} zasobów opieki</p><Button secondary onClick={()=>{if(v.scenario){updateScenario(normalizeScenario(v.scenario));setModal(null);navigate('plan')}}}>Odtwórz warunki jako nową edycję</Button></details>)}</div><Button danger onClick={()=>setModal('delete')}><Trash2 size={16}/>Usuń bieżący plan</Button></Modal>
 <Modal open={modal==='delete'} onOpenChange={v=>!v&&setModal(null)} title="Usunąć plan i jego historię?" description="To usunie plan, ustalenia, obserwacje i wersje z aplikacji. Wcześniej pobranych plików nie można zdalnie cofnąć.">{errorAlert}<div className="modal-actions"><Button secondary onClick={()=>setModal('manage')}>Zachowaj plan</Button><Button danger disabled={busy} onClick={deletePlan}>Usuń plan i powiązane dane</Button></div></Modal>
 <Modal open={modal==='reset'} onOpenChange={v=>!v&&setModal(null)} title={pendingExample?'Otworzyć przykład?':'Zacząć nowy plan?'} description="Niezapisane dane obecnego formularza zostaną zastąpione. Zapisany plan pozostanie na liście Twoich planów.">{errorAlert}<div className="modal-actions"><Button secondary onClick={()=>setModal(null)}>Wróć do edycji</Button><Button onClick={()=>reset(pendingExample)}>{pendingExample?'Otwórz przykład':'Otwórz pusty formularz'}</Button></div></Modal>
 <Modal open={modal==='privacy'} onOpenChange={v=>!v&&setModal(null)} title="Prywatność, którą możesz zrozumieć" description="Używamy tylko danych potrzebnych do sprawdzenia planu.">{errorAlert}<div className="privacy-points"><p><strong>Bez zapisu:</strong> formularz jest w pamięci przeglądarki. Zamknięcie strony usuwa niezapisany formularz. Dane do obliczeń trafiają do naszego API, więc nie jest to przetwarzanie wyłącznie lokalne.</p><p><strong>Po dobrowolnym zapisie:</strong> dostęp chroni losowa sesja w cookie HttpOnly. Utrata cookie może odebrać dostęp. Kopia JSON pozwala odtworzyć plan.</p><p><strong>W rozmowie:</strong> odbiorca widzi dokładnie zatwierdzoną kartę. Nie wysyłamy wiadomości ani nie rezerwujemy miejsca opieki.</p><p><strong>Bez AI w prywatnym planie:</strong> obliczenia wykonuje solver. Prywatny harmonogram nie jest wysyłany do dostawcy modelu.</p><p><strong>Dojazdy:</strong> aktywny tryb {routingMode==='otp'?'OpenTripPlanner, z informacją o ważności tras':'własnych czasów przejazdu, z jawnym źródłem i ważnością'}.</p><p><strong>Kontrola:</strong> możesz pobrać kopię, sprawdzić historię albo usunąć plan. Nie wpisuj nazwisk, diagnoz ani pełnych kalendarzy innych osób.</p></div><Button secondary onClick={()=>{setModal('saved')}}><CircleHelp size={16}/>Moje zapisane plany</Button></Modal><input ref={importInput} type="file" accept="application/json,.json" className="sr-only" aria-label="Wybierz kopię planu JSON" onChange={e=>importBackup(e.target.files?.[0])}/></div>;
}
export default App;

