import { BookOpen, ExternalLink, RefreshCw, Search } from 'lucide-react';
import { useState } from 'react';
import { Badge, Button, Empty, Field, Money, Notice, SectionTitle, formatDate } from './ui';
import type { AnyRecord } from './types';

type CatalogMode='verified'|'synthetic'|'all';
const fieldLabels:Record<string,string>={hours:'Godziny',cost_grosze:'Kwota składnika',cost_component:'Zakres opłaty',ongoing_care_cost:'Koszt bieżącej opieki',food_cost:'Koszt wyżywienia',admission:'Przyjęcie konkretnej osoby',date_exceptions:'Wyjątki w kalendarzu',capacity:'Liczba miejsc',location:'Lokalizacja',cost_period:'Okres opłaty'};
const componentLabels:Record<string,string>={care:'Pobyt / opieka',food:'Wyżywienie',enrollment:'Wpisowe / rekrutacja',additional_care:'Dodatkowa opieka',course:'Kurs / zajęcia',unspecified:'Zakres nieustalony'};
const periodLabels:Record<string,string>={hour:'Za godzinę',day:'Za dzień',month:'Za miesiąc',once:'Jednorazowo'};
function evidenceValue(name:string,value:unknown) {
 if(name==='cost_component')return componentLabels[String(value)]||'Zakres nieustalony';
 if(value==null)return 'Brak potwierdzonej wartości';
 if(name==='cost_grosze'&&typeof value==='number')return <Money grosz={value}/>;
 if(name==='cost_period')return periodLabels[String(value)]||String(value);
 return typeof value==='object'?Object.entries(value).map(([key,item])=>`${key==='start'?'od':key==='end'?'do':key}: ${String(item)}`).join(', '):String(value);
}

export default function Catalog({catalog,mode,onModeChange,onRefresh,busy}:{catalog:AnyRecord|null;mode:CatalogMode;onModeChange:(mode:CatalogMode)=>void;onRefresh:()=>void;busy:boolean}) {
 const [query,setQuery]=useState('');
 const entries:Array<AnyRecord>=Array.isArray(catalog)?catalog:catalog?.records||catalog?.items||[];
 const filtered=entries.filter(e=>JSON.stringify(e).toLocaleLowerCase('pl').includes(query.toLocaleLowerCase('pl')));
 return <div><SectionTitle eyebrow="Przejrzyste pochodzenie danych" title="Źródła, które możesz sprawdzić" description="Znajdź publiczne informacje o usługach i sprawdź ich aktualność."><Button secondary disabled={busy} onClick={onRefresh}><RefreshCw size={16}/>Odśwież</Button></SectionTitle>
 <div className="panel"><Field label="Zakres katalogu"><select value={mode} disabled={busy} onChange={e=>onModeChange(e.target.value as CatalogMode)}><option value="verified">Publiczne źródła po przeglądzie</option><option value="synthetic">Przykłady syntetyczne</option><option value="all">Wszystkie, z oznaczeniem pochodzenia</option></select></Field><p className="small">Wybór źródeł nie zmienia danych ani uzgodnień w Twoim planie.</p></div>
 <Notice tone={mode==='synthetic'?'warning':'info'}>{mode==='synthetic'?<><strong>To dane demonstracyjne.</strong> Nie odnoszą się do realnej dostępności usług.</>:<><strong>Godziny, koszt i przyjęcie konkretnej osoby wymagają potwierdzenia.</strong> Publiczny rekord nie jest rezerwacją. Własną ofertę lub usługę możesz wpisać do planu.</>}</Notice>
 <label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Szukaj w źródłach" aria-label="Szukaj w katalogu"/></label>
 <p className="small" role="status" aria-live="polite" aria-atomic="true">{busy?'Wczytuję wybrany zakres źródeł…':`Liczba wyników: ${filtered.length}.`}</p><div className="catalog-grid" aria-busy={busy}>{filtered.map((item,i)=>{
  const synthetic=item.synthetic||item.data_mode==='synthetic'||item.status==='synthetic';const hours=item.fields?.hours?.value;
  const cost=item.fields?.cost_grosze?.value;const component=item.fields?.cost_component?.value;const period=item.fields?.cost_period?.value;
  const missing=[...new Set<string>([...(item.missing_fields||item.missing||[]),...(cost==null?['cost_grosze']:[]),...(!component||component==='unspecified'||!componentLabels[component]?['cost_component']:[]),...(!period?['cost_period']:[])])];
  return <article className="panel catalog-card" key={item.id||i}><div className="row"><span className="catalog-icon"><BookOpen size={20}/></span><Badge tone={synthetic?'amber':item.status==='published'?'green':'neutral'}>{synthetic?'Dane syntetyczne':item.status==='published'?'Publiczny rekord po przeglądzie':item.status==='stale'?'Wymaga aktualizacji':item.status==='withdrawn'?'Wycofany':'Do sprawdzenia'}</Badge></div><h3>{item.title||item.name||item.label}</h3><p>{item.description||item.summary||'Sprawdź szczegóły i pochodzenie informacji przed użyciem.'}</p><dl className="source-list">{item.kind&&<div><dt>Rodzaj</dt><dd>{({care:'Opieka',adult_care:'Opieka nad dorosłymi',course:'Szkolenie',work:'Praca',directory:'Rejestr źródeł'} as Record<string,string>)[item.kind]||item.kind}</dd></div>}{hours?.start&&hours?.end&&<div><dt>Godziny w źródle</dt><dd>{hours.start} do {hours.end}</dd></div>}<div><dt>Kwota składnika</dt><dd>{evidenceValue('cost_grosze',cost)}</dd></div><div><dt>Dotyczy</dt><dd>{evidenceValue('cost_component',component)}</dd></div><div><dt>Okres opłaty</dt><dd>{evidenceValue('cost_period',period)}</dd></div><div><dt>Sprawdzono</dt><dd>{formatDate(item.checked_at||item.verified_at||item.source?.checked_at)}</dd></div>{(item.valid_to||item.source?.valid_to)&&<div><dt>Ważność</dt><dd>{formatDate(item.valid_to||item.source.valid_to)}</dd></div>}</dl><p className="small">Kwota dotyczy wskazanego składnika. Pozostałe opłaty wymagają osobnego potwierdzenia.</p>{missing.length>0&&<p className="missing-fields">Do potwierdzenia: {missing.map((field:string)=>fieldLabels[field]||field).join(', ')}.</p>}{!synthetic&&<p className="small">Publikacja rekordu nie potwierdza przyjęcia konkretnej osoby.</p>}{(item.url||item.source_url||item.source?.url)&&<a className="text-link" href={item.url||item.source_url||item.source.url} target="_blank" rel="noreferrer">Otwórz źródło<ExternalLink size={15}/></a>}<details className="details"><summary>Pochodzenie poszczególnych pól</summary>{Object.entries(item.fields||{}).map(([name,evidence])=>{const field=evidence as AnyRecord;return <div className="availability" key={name}><h4>{fieldLabels[name]||name}</h4><p>{evidenceValue(name,field.value)}</p>{field.excerpt&&<blockquote>{field.excerpt}</blockquote>}<p className="small">Sprawdzono: {formatDate(field.checked_at)}. {field.status==='reviewed'?'Pole po przeglądzie.':field.status==='synthetic'?'Pole syntetyczne.':'Wymaga sprawdzenia.'}</p>{field.source_url&&<a className="text-link" href={field.source_url} target="_blank" rel="noreferrer">Źródło pola<ExternalLink size={13}/></a>}</div>})}</details></article>;
 })}</div>{!busy&&filtered.length===0&&<Empty title={query?'Nie ma pasujących źródeł':'Wybrany zakres nie zawiera rekordów'}>Zmień zakres katalogu lub dodaj własne dane w zakładce Twój plan. Własne dane są pełnoprawnym sposobem korzystania z Okna.</Empty>}</div>;
}
