import { useState } from 'react';
import { MapPin, Route } from 'lucide-react';
import { apiPost } from './api';
import { Badge, Button, Field, Money, Notice, formatDate } from './ui';
import type { AnyRecord, Scenario, TravelLeg } from './types';

function warsawTime(date:string,time:string,fold:string):string {
 const formatter=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
 const values=['+02:00','+01:00'].map(offset=>`${date}T${time}:00${offset}`).filter(value=>{const parsed=new Date(value);return !Number.isNaN(parsed.getTime())&&formatter.format(parsed)===`${date} ${time}`});
 if(!values.length)throw new Error('Ta godzina nie istnieje w strefie Europe/Warsaw. Sprawdź datę i zmianę czasu.');
 if(values.length>1&&!fold)throw new Error('Ta godzina występuje dwa razy. Wybierz pierwsze lub drugie wystąpienie.');
 return values[fold==='1'?values.length-1:0];
}

export function LocationCoordinates({scenario,onChange}:{scenario:Scenario;onChange:(coordinates:Scenario['location_coordinates'])=>void}) {
 const [drafts,setDrafts]=useState<Record<string,{lat:string;lon:string}>>({});
 const locations=[...new Set([scenario.home_location,...scenario.activities.map(a=>a.location),...scenario.care_resources.map(r=>r.location),...scenario.travel_legs.flatMap(t=>[t.origin,t.destination])])].filter(Boolean);
 return <details className="details"><summary><MapPin size={16}/>Punkty do obliczenia tras komunikacją i pieszo</summary><p>Podaj współrzędne punktu orientacyjnego. Dokładny adres nie jest potrzebny. Gdy obie lokalizacje mają współrzędne, analiza sprawdzi trasy ponownie dla każdej dopuszczalnej godziny pracy.</p>{locations.map(name=>{const point=scenario.location_coordinates[name];const draft=drafts[name]||{lat:point?String(point.lat):'',lon:point?String(point.lon):''};const valid=draft.lat!==''&&draft.lon!==''&&Number.isFinite(Number(draft.lat))&&Number.isFinite(Number(draft.lon))&&Math.abs(Number(draft.lat))<=90&&Math.abs(Number(draft.lon))<=180;return <div className="availability" key={name}><h4>{name}</h4><div className="form-grid"><Field label={`Szerokość geograficzna: ${name}`}><input type="number" min="-90" max="90" step="any" placeholder="Nie podano" value={draft.lat} onChange={e=>setDrafts({...drafts,[name]:{...draft,lat:e.target.value}})}/></Field><Field label={`Długość geograficzna: ${name}`}><input type="number" min="-180" max="180" step="any" placeholder="Nie podano" value={draft.lon} onChange={e=>setDrafts({...drafts,[name]:{...draft,lon:e.target.value}})}/></Field></div><Button secondary disabled={!valid} onClick={()=>onChange({...scenario.location_coordinates,[name]:{lat:Number(draft.lat),lon:Number(draft.lon)}})}>{point?'Aktualizuj punkt':'Dodaj punkt do planu'}</Button>{point&&<><Badge tone="green">W planie: {point.lat}, {point.lon}</Badge><button className="text-button" onClick={()=>{const next={...scenario.location_coordinates};delete next[name];onChange(next)}}>Usuń punkt z planu</button></>}</div>})}<p className="small">Współrzędne służą własnej usłudze tras. Nie trafiają do modelu językowego. Bez współrzędnych nadal możesz wpisać własny czas przejazdu.</p></details>;
}

export default function RoutePlanner({leg,scenario,onChange}:{leg:TravelLeg;scenario:Scenario;onChange:(leg:TravelLeg)=>void}) {
 const [date,setDate]=useState(scenario.start_date);const [time,setTime]=useState('08:00');const [fold,setFold]=useState('');const [arrive,setArrive]=useState(false);const [access,setAccess]=useState(leg.access_minutes||0);const [pending,setPending]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<AnyRecord|null>(null);
 const calculated=leg.mode==='walk'||leg.mode==='transit';const from=scenario.location_coordinates[leg.origin];const to=scenario.location_coordinates[leg.destination];
 const check=async()=>{setPending(true);setError('');setResult(null);try{const response=await apiPost('/api/routes',{queries:[{id:leg.id,origin:leg.origin,destination:leg.destination,when:warsawTime(date,time,fold),arrive_by:arrive,mode:leg.mode==='transit'?'transit':leg.mode==='walk'?'walk':'manual',...(calculated?{from_point:from,to_point:to}:{manual_leg:leg}),access_minutes:calculated?access:0,handoff_minutes:leg.handoff_minutes,buffer_minutes:leg.buffer_minutes,cost_grosze:leg.bands[0]?.cost_grosze??null}]});setResult(response.routes[0]);}catch(e){setError((e as Error).message)}finally{setPending(false)}};
 return <details className="details"><summary><Route size={16}/>Sprawdź ten odcinek dla konkretnej godziny</summary><div className="form-grid"><Field label="Dzień podróży"><input type="date" value={date} onChange={e=>{setDate(e.target.value);setResult(null)}}/></Field><Field label="Godzina w Polsce"><input type="time" value={time} onChange={e=>{setTime(e.target.value);setResult(null)}}/></Field><Field label="Godzina oznacza"><select value={arrive?'arrival':'departure'} onChange={e=>{setArrive(e.target.value==='arrival');setResult(null)}}><option value="departure">Wyjście z miejsca</option><option value="arrival">Gotowość na miejscu z buforem</option></select></Field><Field label="Przy zmianie czasu"><select value={fold} onChange={e=>{setFold(e.target.value);setResult(null)}}><option value="">Godzina jednoznaczna</option><option value="0">Pierwsze wystąpienie</option><option value="1">Drugie wystąpienie</option></select></Field>{calculated&&<Field label="Dodatkowy dojściowy odcinek od punktu (min)"><input type="number" min="0" max="180" value={access} onChange={e=>{setAccess(Number(e.target.value));setResult(null)}}/></Field>}</div>{calculated&&(!from||!to)&&<Notice tone="warning">Dodaj współrzędne obu miejsc w sekcji punktów powyżej. Alternatywnie wybierz własny zmierzony czas.</Notice>}<Button secondary disabled={pending||!date||!time||(calculated&&(!from||!to))} onClick={check}>{pending?'Sprawdzam trasę…':'Sprawdź przejazd'}</Button>{error&&<p role="alert" className="error-text">{error}</p>}{result&&<div className="route-result"><Badge tone={result.status==='ok'?'green':'amber'}>{result.status==='ok'?'Trasa sprawdzona':'Trasa wymaga danych'}</Badge>{result.status==='ok'?<><p>Podróż: <strong>{result.minutes} min</strong>. Razem z przekazaniem i buforem: <strong>{result.total_minutes} min</strong>. Koszt: <Money grosz={result.cost_grosze}/>.</p><p className="small">Źródło: {result.source?.label}. Ważność: {formatDate(result.source?.valid_from)} do {formatDate(result.source?.valid_to)}.</p>{result.limitations?.map((item:string)=><p className="small" key={item}>{item}</p>)}{calculated&&<Button secondary onClick={()=>{onChange({...result.leg,bands:[...leg.bands.filter(b=>JSON.stringify(b)!==JSON.stringify(result.leg.bands[0])),...result.leg.bands]});setResult(null)}}>Zachowaj sprawdzony odcinek</Button>}</>:<p>{result.reason}</p>}</div>}</details>;
}
