import { useRef, type ReactNode } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { X, ArrowRight, Check, Info, AlertTriangle, ShieldCheck } from 'lucide-react';
export function Button({children,secondary=false,danger=false,className='',...props}: React.ButtonHTMLAttributes<HTMLButtonElement> & {secondary?:boolean;danger?:boolean}) { return <button className={`button ${secondary ? 'secondary' : ''} ${danger ? 'danger' : ''} ${className}`} {...props}>{children}</button>; }
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}) {return <span className={`badge ${tone}`}>{children}</span>;}
export function Notice({children,tone='info'}:{children:ReactNode;tone?:string}) {const Icon=tone==='warning'?AlertTriangle:tone==='success'?Check:Info;return <div className={`notice ${tone}`}><Icon size={19} aria-hidden/><div>{children}</div></div>;}
export function Field({label,hint,children}:{label:string;hint?:string;children:ReactNode}) {return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function SectionTitle({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:ReactNode}) {return <div className="section-title"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{description&&<p>{description}</p>}</div>{children}</div>;}
export function Modal({open,onOpenChange,title,description,children}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;description:string;children:ReactNode}) {
 const opener=useRef<HTMLElement|null>(null);
 return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="modal" onOpenAutoFocus={()=>{opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null}} onCloseAutoFocus={event=>{event.preventDefault();if(document.querySelector('[role="dialog"][data-state="open"]'))return;const target=opener.current?.isConnected?opener.current:document.getElementById('main-content');target?.focus()}}><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description}</Dialog.Description><Dialog.Close className="icon-button close" aria-label="Zamknij okno"><X size={21}/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;
}
export function Empty({title,children,action,onAction}:{title:string;children:ReactNode;action?:string;onAction?:()=>void}) {return <div className="empty"><span className="empty-icon"><ShieldCheck size={28}/></span><h3>{title}</h3><p>{children}</p>{action&&<Button onClick={onAction}>{action}<ArrowRight size={17}/></Button>}</div>;}
export function Money({grosz}:{grosz:number|null|undefined}) {return <>{grosz == null?'Nieznany koszt':new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:2}).format(grosz/100)}</>;}
export function displayTime(value:number|string|undefined|null) {if(value==null)return 'Nie podano';if(typeof value==='string')return value.includes('T')?value.slice(11,16):value;return `${Math.floor(value/60).toString().padStart(2,'0')}:${(value%60).toString().padStart(2,'0')}`;}
export function formatDate(date:string|undefined) {return date?new Intl.DateTimeFormat('pl-PL',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${date.slice(0,10)}T12:00:00`)):'Nie podano';}
